---
- :name: Gamma formalism
  :author: Erich Gamma Richard Helm Ralph Johnson & John Vlissides
  :version: 1.0.0
  :description: The classic formalism designed by the Gang of Four. Should be used for describing software architectures.
  :pattern_formalisms:
  - :name: Software architecture pattern
    :field_descriptors:
    - :name: Classification
      :section: interface
      :field_type: classification
      :is_sorting_patterns: true
      :description: Category the pattern belongs to
    - :name: Also known as
      :section: interface
      :field_type: string
      :description: Synonyms for the pattern name
    - :name: Motivation
      :section: interface
      :field_type: text
      :description: Describes the situations for which the pattern would be relevant
    - :name: Applicability
      :section: interface
      :field_type: text
      :description: Describes the situtations for which the pattern would be relevant
    -  :name: Structure
       :section: solution
       :field_type: mappable_image  # A set of commented models
       :description: Describes formal software architecture solutions
    -  :name: Solution participants
       :section: solution
       :field_type: text
       :description: A textual solution that describes the entities of the formal solution
    -  :name: Collaborations
       :section: solution
       :field_type: text
       :description: A textual solution that describes the interactions between the entities of the formal solution
    -  :name: Consequence
       :section: solution
       :field_type: text
       :description: Presents the consequences related to the application of the pattern
    -  :name: Implementation
       :section: solution
       :field_type: text
       :description: Presents pragmatic software-related elements related to the implementation of the solution's software architecture
    -  :name: Sample code
       :section: solution
       :field_type: text
       :description: Presents some code samples that illustrate the implementation of the pattern
    -  :name: Known uses
       :section: solution
       :field_type: text
       :description: Describes some actual uses of the pattern taken from existing applications
    -  :name: Related patterns
       :section: solution
       :field_type: text
       :description: Enumerates some patterns from the system that are somehow related to the current pattern
- :name: P-SIGMA formalism
  :author: SIGMA team, LIG Laboratory, Grenoble
  :version: 1.0.0
  :description: A formalism adapted to the description of complex processes. Also includes product patterns.
  :pattern_formalisms:
  - :name: Process pattern
    :is_main_pattern: true
    :field_descriptors:
      - :name: Classification
        :section: interface
        :field_type: multi_classification
      - :name: Context
        :section: interface
        :field_type: text
        :description: Describes the organisational context in which the activity should take place
      - :name: Strengths
        :section: interface
        :field_type: text
        :description: The specific assets of the pattern, given the context
      - :name: Visual solution
        :section: solution
        :field_type: mappable_image
        :description: A visual description of the sub-activities organization
      - :name: Text solution
        :section: solution
        :field_type: text
        :description: A textual description of each sub-activity
      - :name: Application cases
        :section: solution
        :field_type: text
        :description: Describes an actual use of the pattern, taken from existing project instances.
      - :name: Application consequences
        :section: solution
        :field_type: text
        :description: Describes the consequences that follow the realization of the pattern's activities.
  - :name: Product pattern
    :field_descriptors:
      - :name: Classification
        :section: interface
        :field_type: multi_classification
      - :name: Strengths
        :section: interface
        :field_type: text
      - :name: Visual solution
        :section: solution
        :field_type: mappable_image
      - :name: Text solution
        :section: solution
        :field_type: text
      - :name: Application cases
        :section: solution
        :field_type: text
      - :name: Application consequences
        :section: solution
        :field_type: text
  :relation_descriptors:
    - :name: Alternative
      :is_reflexive: true
      :associated_field_name: Strengths
      :associated_field_description: The following pattern(s) address the same issue(s), but focus on the following intents
    - :name: Refine
      :associated_field_name: Problem
      :associated_field_description: The following pattern(s) address a more specific problem
